In [114]:
import numpy as np
import pandas as pd

In [115]:
df1 = pd.read_csv("/kaggle/input/datasets/vjchoudhary7/hr-analytics-case-study/employee_survey_data.csv")
df2 = pd.read_csv("/kaggle/input/datasets/vjchoudhary7/hr-analytics-case-study/general_data.csv")
df3 = pd.read_csv("/kaggle/input/datasets/vjchoudhary7/hr-analytics-case-study/in_time.csv")
df4 = pd.read_csv("/kaggle/input/datasets/vjchoudhary7/hr-analytics-case-study/manager_survey_data.csv")
df5 = pd.read_csv("/kaggle/input/datasets/vjchoudhary7/hr-analytics-case-study/out_time.csv")

In [116]:
df2.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [117]:
col = df2.pop("EmployeeID")
df2.insert(0, 'EmployeeID', col)

In [118]:
df2.head()

,EmployeeID,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,1,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,2,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,3,32,No,Travel_Frequently,Research & Development,17,4,Other,1,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,4,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,5,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [119]:
df3.head()

,Unnamed: 0,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaN,2015-01-02 09:43:45,2015-01-05 10:08:48,2015-01-06 09:54:26,2015-01-07 09:34:31,2015-01-08 09:51:09,2015-01-09 10:09:25,2015-01-12 09:42:53,2015-01-13 10:13:06,...,NaN,2015-12-21 09:55:29,2015-12-22 10:04:06,2015-12-23 10:14:27,2015-12-24 10:11:35,NaN,2015-12-28 10:13:41,2015-12-29 10:03:36,2015-12-30 09:54:12,2015-12-31 10:12:44
1,2,NaN,2015-01-02 10:15:44,2015-01-05 10:21:05,NaN,2015-01-07 09:45:17,2015-01-08 10:09:04,2015-01-09 09:43:26,2015-01-12 10:00:07,2015-01-13 10:43:29,...,2015-12-18 10:37:17,2015-12-21 09:49:02,2015-12-22 10:33:51,2015-12-23 10:12:10,NaN,NaN,2015-12-28 09:31:45,2015-12-29 09:55:49,2015-12-30 10:32:25,2015-12-31 09:27:20
2,3,NaN,2015-01-02 10:17:41,2015-01-05 09:50:50,2015-01-06 10:14:13,2015-01-07 09:47:27,2015-01-08 10:03:40,2015-01-09 10:05:49,2015-01-12 10:03:47,2015-01-13 10:21:26,...,2015-12-18 10:15:14,2015-12-21 10:10:28,2015-12-22 09:44:44,2015-12-23 10:15:54,2015-12-24 10:07:26,NaN,2015-12-28 09:42:05,2015-12-29 09:43:36,2015-12-30 09:34:05,2015-12-31 10:28:39
3,4,NaN,2015-01-02 10:05:06,2015-01-05 09:56:32,2015-01-06 10:11:07,2015-01-07 09:37:30,2015-01-08 10:02:08,2015-01-09 10:08:12,2015-01-12 10:13:42,2015-01-13 09:53:22,...,2015-12-18 10:17:38,2015-12-21 09:58:21,2015-12-22 10:04:25,2015-12-23 10:11:46,2015-12-24 09:43:15,NaN,2015-12-28 09:52:44,2015-12-29 09:33:16,2015-12-30 10:18:12,2015-12-31 10:01:15
4,5,NaN,2015-01-02 10:28:17,2015-01-05 09:49:58,2015-01-06 09:45:28,2015-01-07 09:49:37,2015-01-08 10:19:44,2015-01-09 10:00:50,2015-01-12 10:29:27,2015-01-13 09:59:32,...,2015-12-18 09:58:35,2015-12-21 10:03:41,2015-12-22 10:10:30,2015-12-23 10:13:36,2015-12-24 09:44:24,NaN,2015-12-28 10:05:15,2015-12-29 10:30:53,2015-12-30 09:18:21,2015-12-31 09:41:09

In [120]:
df5.head()

,Unnamed: 0,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaN,2015-01-02 16:56:15,2015-01-05 17:20:11,2015-01-06 17:19:05,2015-01-07 16:34:55,2015-01-08 17:08:32,2015-01-09 17:38:29,2015-01-12 16:58:39,2015-01-13 18:02:58,...,NaN,2015-12-21 17:15:50,2015-12-22 17:27:51,2015-12-23 16:44:44,2015-12-24 17:47:22,NaN,2015-12-28 18:00:07,2015-12-29 17:22:30,2015-12-30 17:40:56,2015-12-31 17:17:33
1,2,NaN,2015-01-02 18:22:17,2015-01-05 17:48:22,NaN,2015-01-07 17:09:06,2015-01-08 17:34:04,2015-01-09 16:52:29,2015-01-12 17:36:48,2015-01-13 18:00:13,...,2015-12-18 18:31:28,2015-12-21 17:34:16,2015-12-22 18:16:35,2015-12-23 17:38:18,NaN,NaN,2015-12-28 17:08:38,2015-12-29 17:54:46,2015-12-30 18:31:35,2015-12-31 17:40:58
2,3,NaN,2015-01-02 16:59:14,2015-01-05 17:06:46,2015-01-06 16:38:32,2015-01-07 16:33:21,2015-01-08 17:24:22,2015-01-09 16:57:30,2015-01-12 17:28:54,2015-01-13 17:21:25,...,2015-12-18 17:02:23,2015-12-21 17:20:17,2015-12-22 16:32:50,2015-12-23 16:59:43,2015-12-24 16:58:25,NaN,2015-12-28 16:43:31,2015-12-29 17:09:56,2015-12-30 17:06:25,2015-12-31 17:15:50
3,4,NaN,2015-01-02 17:25:24,2015-01-05 17:14:03,2015-01-06 17:07:42,2015-01-07 16:32:40,2015-01-08 16:53:11,2015-01-09 17:19:47,2015-01-12 17:13:37,2015-01-13 17:11:45,...,2015-12-18 17:55:23,2015-12-21 16:49:09,2015-12-22 17:24:00,2015-12-23 17:36:35,2015-12-24 16:48:21,NaN,2015-12-28 17:19:34,2015-12-29 16:58:16,2015-12-30 17:40:11,2015-12-31 17:09:14
4,5,NaN,2015-01-02 18:31:37,2015-01-05 17:49:15,2015-01-06 17:26:25,2015-01-07 17:37:59,2015-01-08 17:59:28,2015-01-09 17:44:08,2015-01-12 18:51:21,2015-01-13 18:14:58,...,2015-12-18 17:52:48,2015-12-21 17:43:35,2015-12-22 18:07:57,2015-12-23 18:00:49,2015-12-24 17:59:22,NaN,2015-12-28 17:44:59,2015-12-29 18:47:00,2015-12-30 17:15:33,2015-12-31 17:42:14

In [121]:
df3 = df3.rename(columns={'Unnamed: 0': 'EmployeeID'})
df5 = df5.rename(columns={'Unnamed: 0': 'EmployeeID'})

In [122]:
df6 = pd.merge(df1, df4, on = 'EmployeeID')
df7 = pd.merge(df6, df2, on = 'EmployeeID')
df8 = pd.merge(df3, df5, on = 'EmployeeID')
df_final = pd.merge(df7, df8, on = 'EmployeeID')

In [123]:
df_final.head()

,EmployeeID,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating,Age,Attrition,BusinessTravel,Department,...,2015-12-18_y,2015-12-21_y,2015-12-22_y,2015-12-23_y,2015-12-24_y,2015-12-25_y,2015-12-28_y,2015-12-29_y,2015-12-30_y,2015-12-31_y
0,1,3.0,4.0,2.0,3,3,51,No,Travel_Rarely,Sales,...,NaN,2015-12-21 17:15:50,2015-12-22 17:27:51,2015-12-23 16:44:44,2015-12-24 17:47:22,NaN,2015-12-28 18:00:07,2015-12-29 17:22:30,2015-12-30 17:40:56,2015-12-31 17:17:33
1,2,3.0,2.0,4.0,2,4,31,Yes,Travel_Frequently,Research & Development,...,2015-12-18 18:31:28,2015-12-21 17:34:16,2015-12-22 18:16:35,2015-12-23 17:38:18,NaN,NaN,2015-12-28 17:08:38,2015-12-29 17:54:46,2015-12-30 18:31:35,2015-12-31 17:40:58
2,3,2.0,2.0,1.0,3,3,32,No,Travel_Frequently,Research & Development,...,2015-12-18 17:02:23,2015-12-21 17:20:17,2015-12-22 16:32:50,2015-12-23 16:59:43,2015-12-24 16:58:25,NaN,2015-12-28 16:43:31,2015-12-29 17:09:56,2015-12-30 17:06:25,2015-12-31 17:15:50
3,4,4.0,4.0,3.0,2,3,38,No,Non-Travel,Research & Development,...,2015-12-18 17:55:23,2015-12-21 16:49:09,2015-12-22 17:24:00,2015-12-23 17:36:35,2015-12-24 16:48:21,NaN,2015-12-28 17:19:34,2015-12-29 16:58:16,2015-12-30 17:40:11,2015-12-31 17:09:14
4,5,4.0,1.0,3.0,3,3,32,No,Travel_Rarely,Research & Development,...,2015-12-18 17:52:48,2015-12-21 17:43:35,2015-12-22 18:07:57,2015-12-23 18:00:49,2015-12-24 17:59:22,NaN,2015-12-28 17:44:59,2015-12-29 18:47:00,2015-12-30 17:15:33,2015-12-31 17:42:14

In [124]:
df_final.isnull().sum()

EmployeeID                    0
EnvironmentSatisfaction      25
JobSatisfaction              20
WorkLifeBalance              38
JobInvolvement                0
                           ...
2015-12-25_y               4410
2015-12-28_y                234
2015-12-29_y                230
2015-12-30_y                265
2015-12-31_y                213
Length: 551, dtype: int64

In [125]:
mode_job = df_final['JobSatisfaction'].mode()[0]
df_final['JobSatisfaction'] = df_final['JobSatisfaction'].fillna(mode_job)

In [126]:
mode_env = df_final['EnvironmentSatisfaction'].mode()[0]
df_final['EnvironmentSatisfaction'] = df_final['EnvironmentSatisfaction'].fillna(mode_env)

In [127]:
mode_work = df_final['WorkLifeBalance'].mode()[0]
df_final['WorkLifeBalance'] = df_final['WorkLifeBalance'].fillna(mode_work)

In [128]:
mode_comp = df_final['NumCompaniesWorked'].mode()[0]
df_final['NumCompaniesWorked'] = df_final['NumCompaniesWorked'].fillna(mode_comp)

In [129]:
mode_year = df_final['TotalWorkingYears'].mode()[0]
df_final['TotalWorkingYears'] = df_final['TotalWorkingYears'].fillna(mode_year)

In [130]:
def rename_attendance(col):
    if col.endswith('_x'):
        date = col.replace('_x','')
        return f'In_{date}'
    elif col.endswith('_y'):
        date = col.replace('_y','')
        return f'Out_{date}'
    else:
        return col

df_final.columns = [rename_attendance(col) for col in df_final.columns]

In [131]:
nan_percentage = df_final.isna().mean()
cols_to_drop = nan_percentage[nan_percentage > 0.30].index
df_final = df_final.drop(columns=cols_to_drop)

In [132]:
print(len(cols_to_drop))
print(cols_to_drop)
print(df_final.shape)

24
Index(['In_2015-01-01', 'In_2015-01-14', 'In_2015-01-26', 'In_2015-03-05',
       'In_2015-05-01', 'In_2015-07-17', 'In_2015-09-17', 'In_2015-10-02',
       'In_2015-11-09', 'In_2015-11-10', 'In_2015-11-11', 'In_2015-12-25',
       'Out_2015-01-01', 'Out_2015-01-14', 'Out_2015-01-26', 'Out_2015-03-05',
       'Out_2015-05-01', 'Out_2015-07-17', 'Out_2015-09-17', 'Out_2015-10-02',
       'Out_2015-11-09', 'Out_2015-11-10', 'Out_2015-11-11', 'Out_2015-12-25'],
      dtype='object')
(4410, 527)

In [133]:
attendance_cols = [col for col in df_final.columns if col.startswith('In_') or col.startswith('Out_')]
df_final[attendance_cols] = df_final[attendance_cols].applymap(
    lambda x: str(x).split(' ')[-1] if pd.notna(x) else x
)

/tmp/ipykernel_55/945662569.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_final[attendance_cols] = df_final[attendance_cols].applymap(

In [134]:
in_cols = [col for col in attendance_cols if col.startswith('In_')]

In [135]:
def time_to_minutes(t):
    if pd.isna(t):
        return t
    h, m, s = map(int, t.split(':'))
    return h*60 + m

df_final[attendance_cols] = df_final[attendance_cols].applymap(time_to_minutes)

/tmp/ipykernel_55/361967692.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_final[attendance_cols] = df_final[attendance_cols].applymap(time_to_minutes)

In [136]:
out_cols = [col for col in attendance_cols if col.startswith('Out_')]
work_cols = []

for in_col in in_cols:
    
    date = in_col.replace('In_', '')
    out_col = f'Out_{date}'
    
    if out_col in df_final.columns:
        
        work_col = f'Work_{date}'
        
        df_final[work_col] = df_final[out_col] - df_final[in_col]
        
        work_cols.append(work_col)

df_final['avg_work_hours'] = df_final[work_cols].mean(axis=1)
df_final['avg_work_hours'] = df_final['avg_work_hours'] / 60

/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]
/tmp/ipykernel_55/4116321372.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[work_col] = df_final[out_col] - df_final[in_col]

In [137]:
in_cols = [col for col in attendance_cols if col.startswith('In_')]
all_in_times = df_final[in_cols].stack()
mode_in_time = all_in_times.mode()[0]

In [138]:
in_cols = [col for col in attendance_cols if col.startswith('In_')]
df_final['avg_in_time'] = df_final[in_cols].mean(axis=1)
df_final['avg_in_time'] = df_final['avg_in_time'].round().astype(int)

/tmp/ipykernel_55/496069885.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['avg_in_time'] = df_final[in_cols].mean(axis=1)

In [139]:
df_final[['avg_in_time']].head()

   avg_in_time
0          600
1          599
2          601
3          598
4          599

In [140]:
df_final['work_hour_std'] = df_final[work_cols].std(axis=1)
df_final['work_hour_std'] = df_final['work_hour_std'] / 60

/tmp/ipykernel_55/1852036909.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['work_hour_std'] = df_final[work_cols].std(axis=1)

In [141]:
df_final[['work_hour_std']].head()

   work_hour_std
0       0.282365
1       0.312997
2       0.311622
3       0.283689
4       0.300795

In [142]:
late_matrix = df_final[in_cols] > mode_in_time

df_final['late_ratio'] = late_matrix.sum(axis=1) / df_final[in_cols].notna().sum(axis=1)

/tmp/ipykernel_55/2280769698.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['late_ratio'] = late_matrix.sum(axis=1) / df_final[in_cols].notna().sum(axis=1)

In [143]:
df_final['attendance_rate'] = df_final[in_cols].notna().sum(axis=1) / len(in_cols)

/tmp/ipykernel_55/2529150201.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['attendance_rate'] = df_final[in_cols].notna().sum(axis=1) / len(in_cols)

In [144]:
df_final['Attrition'] = df_final.pop('Attrition')

/tmp/ipykernel_55/1505840994.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['Attrition'] = df_final.pop('Attrition')

In [146]:
cols_to_remove = in_cols + out_cols + work_cols

df_final.drop(columns=cols_to_remove, inplace=True)

In [148]:
df_final.columns

Index(['EmployeeID', 'EnvironmentSatisfaction', 'JobSatisfaction',
       'WorkLifeBalance', 'JobInvolvement', 'PerformanceRating', 'Age',
       'BusinessTravel', 'Department', 'DistanceFromHome', 'Education',
       'EducationField', 'EmployeeCount', 'Gender', 'JobLevel', 'JobRole',
       'MaritalStatus', 'MonthlyIncome', 'NumCompaniesWorked', 'Over18',
       'PercentSalaryHike', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'avg_work_hours',
       'avg_in_time', 'work_hour_std', 'late_ratio', 'attendance_rate',
       'Attrition'],
      dtype='object')

In [149]:
df_final['Over18'].nunique()

1

In [150]:
df_final['StandardHours'].nunique()

1

In [151]:
df_final['EmployeeCount'].nunique()

1

In [152]:
df_final.drop(columns=['EmployeeCount', 'StandardHours', 'Over18', 'EmployeeID'], inplace = True)

In [153]:
df_final.columns

Index(['EnvironmentSatisfaction', 'JobSatisfaction', 'WorkLifeBalance',
       'JobInvolvement', 'PerformanceRating', 'Age', 'BusinessTravel',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'Gender', 'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'PercentSalaryHike', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'avg_work_hours',
       'avg_in_time', 'work_hour_std', 'late_ratio', 'attendance_rate',
       'Attrition'],
      dtype='object')

In [154]:
df_final['Attrition'] = df_final['Attrition'].map({'Yes':1, 'No':0})

In [155]:
df_final.isnull().sum()

EnvironmentSatisfaction    0
JobSatisfaction            0
WorkLifeBalance            0
JobInvolvement             0
PerformanceRating          0
Age                        0
BusinessTravel             0
Department                 0
DistanceFromHome           0
Education                  0
EducationField             0
Gender                     0
JobLevel                   0
JobRole                    0
MaritalStatus              0
MonthlyIncome              0
NumCompaniesWorked         0
PercentSalaryHike          0
StockOptionLevel           0
TotalWorkingYears          0
TrainingTimesLastYear      0
YearsAtCompany             0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
avg_work_hours             0
avg_in_time                0
work_hour_std              0
late_ratio                 0
attendance_rate            0
Attrition                  0
dtype: int64

In [165]:
x = df_final.drop('Attrition', axis=1)
y = df_final['Attrition']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42, stratify=y
)

In [166]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

In [167]:
categorical_cols = [
    'BusinessTravel',
    'Department',
    'EducationField',
    'Gender',
    'JobRole',
    'MaritalStatus'
]

numerical_cols = [col for col in x.columns if col not in categorical_cols]

In [168]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(drop='first'))
])

In [169]:
preprocessor = ColumnTransformer([
    ('num', num_pipeline, numerical_cols),
    ('cat', cat_pipeline, categorical_cols)
])

In [170]:
model_pipeline = Pipeline([
    ('preprocess', preprocessor),
    ('model', LogisticRegression(max_iter=1000))
])

In [171]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [172]:
model_pipeline.fit(x_train, y_train)
y_pred = model_pipeline.predict(x_test)

In [173]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8582766439909297
[[721  19]
 [106  36]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       740
           1       0.65      0.25      0.37       142

    accuracy                           0.86       882
   macro avg       0.76      0.61      0.64       882
weighted avg       0.84      0.86      0.83       882